// <auto-generated />
using System;
using ForumApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ForumApp.Data.Migrations
{
    [DbContext(typeof(ForumDbContext))]
    [Migration("20230606141412_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ForumApp.Data.Models.Post", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1500)
                        .HasColumnType("nvarchar(1500)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(1500)
                        .HasColumnType("nvarchar(1500)");

                    b.HasKey("Id");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0e98f5b2-bf9f-46f6-b565-0f6ca8a5cf81"),
                            Content = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut tempor placerat metus, eget feugiat risus viverra vitae. Integer sit amet.",
                            Title = "My first post"
                        },
                        new
                        {
                            Id = new Guid("8d693bd5-d8ad-482a-8ebe-a59a2578ca49"),
                            Content = "Lorem ipsum dolor sit amet.",
                            Title = "My second post"
                        },
                        new
                        {
                            Id = new Guid("f2aebb72-1389-4f75-abb4-997b547d3a45"),
                            Content = "Sed quis neque finibus, condimentum.",
                            Title = "My third post"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
